version: "3.7"
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.8.0-beta.5
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - imshow_net
    jupyter:
        container_name: jupyter
        image: ucsde4e/baboon_tracking
        build:
            dockerfile: Dockerfile
            context: ./
        ports:   
            - "8888:8888"
        networks:
            - imshow_net
        volumes:
            - type: bind
              source: ./data
              target: /home/jovyan/baboon_tracking/data
            - type: bind
              source: ./output
              target: /home/jovyan/baboon_tracking/output
        environment:
            - RABBIT_IP='rabbit'
            - RABBIT_PORT='5672'

networks:
    imshow_net:
